### ISSUE TITLE
Pause Menu

### ISSUE THREAD

**Issue by Drakon0168** [RITficialIntelligence/SmashBloc#34]
The game does not resume when you click outside of the menu as it's paused, which then inverts the pause toggle for when you pause in the future.

If you pause the game using escape it brings up the pause menu as you pause it, then if you click outside of the menu the window goes away leaving the game paused. If you then press escape again the menu comes up but the game resumes instead of pausing because it was already paused. To fix this you can just set the game to toggle pause when the mouse is clicked while the game is paused.

**Comment by pgalatic** [comment]
Should be fixed as of the latest merge. Thanks again for the heads-up.
